<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Certpay_Quicksti</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>pratyusha.nulu@zenq.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>293e2d48-ecb5-4f0d-b1a7-f5d4f153ec6c</testSuiteGuid>
   <testCaseLink>
      <guid>8ce6e294-0f9b-4f82-916f-76dd702597e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_001_Visa_SingleLinePayment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d449752b-a4ff-4fca-ad57-df04b58cf612</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Certpay/CertpayTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ef1ae5b-3b6e-4961-9fdc-09734b4d878b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58ba50cf-db6d-4b0e-9b4b-5c7d5be661b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2bbc3d-afb2-48a8-927d-998da730d60a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10edd667-0b6c-4363-8ab7-ff491f04c68c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b986ddc-6d5c-426b-a045-e8d64fd3c568</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65139af-7502-4848-9b94-d83e8cbfed40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5f24328-097f-41f2-a118-3239b2449d3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a613a9e-c2fe-42d9-ac94-5bfb37186634</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5676c55-db28-4e24-8a90-0188cd8b6d2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9afe223-92e6-4e01-9c5b-f9781fe4ba2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d449752b-a4ff-4fca-ad57-df04b58cf612</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>1590139a-81e1-4dae-869f-38490ee03921</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d449752b-a4ff-4fca-ad57-df04b58cf612</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>4d2c9780-e4dc-459c-b576-39b04ec8e088</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a39d1ba-c9b3-4824-a010-ea5e386e9398</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_002_Visa_MultiLinePayment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d88a9ebf-c370-4a8f-b69c-438aba34201b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Certpay/CertpayTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5867bb74-c97e-4bb2-a932-e21f503cb4a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87742eff-1577-45ed-ae28-4d9f7f2182a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c14c95b-4da6-44e2-b046-91027d406b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ada15d24-ceac-4a47-89f8-363ac42e34a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823b5679-d946-4aa4-8364-dfc506853cf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22eb5775-041e-48c6-a5cc-da58937e46ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d88a9ebf-c370-4a8f-b69c-438aba34201b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>37f52433-73a2-466c-8885-6f88e5a96637</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d88a9ebf-c370-4a8f-b69c-438aba34201b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>21b5c1cd-8b6c-4e92-9631-031d22fbfc26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea86cb67-9690-4ad3-a7cc-5447656d9c92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1250170-9252-4bdf-a924-f0b777e45635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb27d6f7-f0fa-49f5-983c-85b6d38bf46e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d75ef3c0-379c-4e20-9b29-a577cde5221c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c2b66c2-142d-462a-8f2e-af5daf26d3a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d65c6bc6-ca59-4721-84fa-7b2bd9b2e84e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8884de0f-9703-40be-8780-ee0158f7e72c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f985841-8fe2-4662-963c-55a653a49399</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b6ee34c-57db-48d9-8937-56f687607893</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_003_MC_SingleLinePayment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7e7f8d06-1cb8-4209-b72a-7edaebde8dda</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Certpay/CertpayTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7e7f8d06-1cb8-4209-b72a-7edaebde8dda</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>2bc21494-1c39-4f4a-8e4a-b033e507029e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7e7f8d06-1cb8-4209-b72a-7edaebde8dda</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>dda101e6-0115-4953-b014-7041ff3bc419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8216a76f-d5f2-4c1d-b92e-d9f9b428483d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f45625e5-eb49-4d14-997b-a4ed6ac2176a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e46479a6-6b14-4a03-a2bc-0284a722a7be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94842996-9038-4203-abbc-9a9cbfa68ced</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2ce0ccd-45cb-4bba-86d1-cc2665d6f40b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3586ef3-dc49-4b19-a27c-2b0d8667fc51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a5ed29-780c-40c2-9791-0c29d370d16b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d62e7d0-20e4-45b9-b70d-b23171f7b218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171505a1-14d8-42e1-b65c-284153193d54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>891d6c84-3b80-4709-aecc-1335322a07ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f7fb333-3ac5-4a92-bbaf-cf41dabcd55f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_004_MC_MultiLInePayment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2ae24bc2-d6ec-4249-99f6-2e50138ad833</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Certpay/CertpayTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed2bea85-8162-4738-9c6e-689ee3450dfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9e375b-4dbf-4369-b3c7-f99019ff60be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44ee101f-2e70-471d-a468-79831a856c57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40509b7e-a85c-4a0e-98aa-021f1fe0b29b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d86f649-c1f5-47e4-ae7c-d2fd2ae60e90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcf92c07-dd4a-4381-99dc-108b783d8769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1460493-36f4-4f5a-b4b1-39f5cfe27449</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be32cf18-4862-496c-b512-977582688df4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2ae24bc2-d6ec-4249-99f6-2e50138ad833</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>b0470b73-45ac-4b37-aa4e-7af42c7af878</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2ae24bc2-d6ec-4249-99f6-2e50138ad833</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>0ee63bd7-7b18-4f7f-b4a6-f7a75bef345d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d1a3a6d-dbe2-4dc6-9583-2b4728bc035f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77320aee-51cc-4434-a4cb-903771118c2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59771a55-432e-4172-89f3-fb09a19e832e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77ca3967-119b-4a0d-9338-394c94e7132a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_005_Discover_SingleLinePayment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>70f3d621-06be-4e05-9907-326f44010345</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Certpay/CertpayTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>70f3d621-06be-4e05-9907-326f44010345</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>3de36bd5-0643-4c65-8ce0-a603e863ee11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>70f3d621-06be-4e05-9907-326f44010345</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>9c73be32-8d24-4a1f-b763-6af5db18a708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14aeeba2-f3e4-4e9e-971d-9217567b1682</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>315a5a1a-b206-487a-a6ef-4b52d2c2eb3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>569a5e3a-ff1c-4a46-a9b5-094a37cbc0e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52b4c48-2a84-42ee-8f03-3bf17ae9c67f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39567b71-a80e-4b43-8a12-dafff799ad3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c542f5a-a6a7-4895-8023-e4007b9a348d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eca2b99-de13-497e-8bb4-bc399efcdd3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6345c54e-8625-4a79-9b5d-102e1003cb86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcef2ab-dc4e-4e6d-994b-76f654e7231d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33a51cda-4edd-40f8-86c4-d60a8ae163a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43f00258-5188-41e8-85fc-62c0fd14cf99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>151498a3-3522-4d7e-83da-8b2e646e225c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57c6cc2f-32bb-40b4-ad53-a8b831759c7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_006_Discover_MultiLInePayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a05a884c-2088-46dc-87de-01205d639aa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41497318-5788-4816-b8a7-2db87fa30aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adc2c14e-6286-437a-8c40-1eaacfbfefb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520e5496-c06b-42eb-b699-9e6cd3eb19cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9806b33f-77e2-45b1-8c21-cd97db42a80f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53973fcd-7208-4e5d-abb7-66722ea7beb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f1cc511-0a05-44e1-8716-ec3517e8366a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad07186-33f2-4cdf-9a8f-6e5fe12f60be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed0d90c2-8558-44c2-9afa-ddf2626829eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cbad6ad-07c7-4ddc-be95-ef8dd732b958</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7be614e-7384-4891-b937-d711b0063b47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d4bbf9-7dc2-4224-a3ee-7bf618056d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39b39cd1-ba08-4194-8449-a538c804fd98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6960ed79-0a92-455d-835c-f9b17b0effe0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_007_Amex_SingleLinePayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4f02e7d-70d8-4437-94a6-fdde1540e39e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c30853ae-96e1-4cfc-9295-ed28508e5aa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6af13380-4a7c-47b5-bf65-8df31a4b0d01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95560e45-8483-49f2-b761-5d9528bfb905</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a57e0c6-5429-4203-b23e-aa17216f8d8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80cbff4d-4ce7-4746-be44-852d9d8ed796</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b0c1f80-25bd-476e-b8b8-ad9c7b9b4145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3030e3c7-b0a5-4cab-9613-857be3b59ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91db5ef9-12e8-4642-b111-eff7e4d38e7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>910d6e40-62e5-4bd4-a89f-3f5034d78ef7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09f479b9-4eba-43f4-b2f2-4689c293f708</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_008_Amex_MultiLinePayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36df1c6c-53e4-479f-b40f-79de5b810135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e710e5a3-59a3-4082-bb4b-8710e02dcebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd1cd249-f03a-424f-9c56-eb8c26fe42cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6775e79-b489-4b92-bfb6-e15c04a9f758</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4968e6fe-3534-46c8-8aa5-5eb31b4a4e47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>305e97f2-3f80-47e5-a48e-69a336f14f14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c621042c-4def-40d9-891d-95b061c814d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a2b0fd5-0d54-4f37-b9fd-61c0c2886fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817d115a-dac4-4bd3-8be3-2a780e8ac723</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c90a02e-93c3-4043-94c4-1b694b857da2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>245f6e4c-e831-4722-a77a-9824e5542d81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0658d4-6d5d-42f1-89ff-ba7db5551638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d038bc3-f4ec-49a6-a785-182c5df140f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8eac287-6bc5-4e02-ad39-e34604477171</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_009_MultiBureauSite_MultiBureau_SingleLinePayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76c243dc-a9b5-4dfe-ba1f-82a5437de749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd2da87-bbd4-485d-a767-bae4e849e515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d0b93c0-0a8e-4794-b7bd-4a95d2a04b5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e665492a-85fd-4bf9-b13b-1403b2b1cf30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff57a7a4-8c18-43c4-92de-6f82577ab03c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cd0a708-3ce0-4685-909c-139777c745c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d923c23b-0b93-4b43-a424-ba8195082364</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba05ee4a-194c-4dc3-842f-8acfd8cc185d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ccc5dae-41f3-4892-9c40-a033e797f006</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>860cf265-70fc-4849-9ccc-d27e8eb5fcc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92ab9b7f-b855-4d21-8723-b9c46bbe1b4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41b1889a-7d6c-41ae-aa16-eb99d2de6435</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b44b707-c65a-476a-9697-5d64dfece0a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd4c579-e9fc-49ab-a690-7d5fb94e4d66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f42a9a28-4dee-4710-80c4-d2a8cb4be8bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_010_MultiBureauSite_MultiBureaus_SingleLinePayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f85d8e-cee5-4531-b42c-a28d45e8653a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b9aed3d-4b35-4816-b629-59b3ba904777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebf43c2e-4381-4d45-b178-e96bb61805e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>274c2f3a-2ff1-4f48-9583-c5fec031ec24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93274ef1-3dd4-41f1-a074-a5c89fadffe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99c60acd-c5f8-435c-b079-1d9a563b9769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4344bec-fd38-42cb-b01f-ea4f94de400e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>284b4fee-bfd0-49f1-94ea-5ff8a3ed93f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aedb1427-089c-4bdd-8da0-5289610de935</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5e0beb1-41ba-4a2e-abd2-e9d114f4f777</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Certpay_Quicksti/TC_011_MultiBureauSite_MultiBureaus_MultiLinePayments</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50950733-fb6b-44e1-9737-005b9b4ec377</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16cb5f58-8762-4c42-89d1-2193e8a57170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37101f1e-910e-44b3-8a25-9684eef3b494</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d73fd393-a012-42a3-85b8-44ed7af933e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1bb9db2-a050-4e12-8552-56a457440fd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1d2beab-75f3-4a1e-936e-ddaf673d2947</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af5be821-5204-4296-a012-d8c0536a464a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8b82dc6-4e43-45c6-9e03-a09057fbd43a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d390254c-1eb3-4e17-89ff-e09c0486acc5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
